descriptions = [
{project_title: 'Deck of Cards',
 description: 'https://github.com/Evan-Price-projects/CardGame Worked in a simulated agile scrum environment with a team of 5. Went through 3 iterations and used programming tools such as RSPEC, HTML.erb, CSS, Ruby, Rails, Github issues, Pivotal Tracker, 4 weekly scrum meetings, SimpleCov,  Sqlite as production and Postgres as development, Heroku Deployment, TDD, BDD, RESTful services.',   images: '1.png, 2.png, 3.png, 4.png, 5.png, 6.png'},
{project_title: 'Logical Programming Language',
 description: 'Created a language called Logic. Solves logical queries. Gained experience in Programming Structure, Haskell, Pair Programming, Automated Testing, Programming Architecture and Advanced Logic.', images: 'haskell1.png, haskell2.png'},
{project_title: 'Black-Box Rotten Tomatoes Testing',
 description: 'Wrote test cases and used Cucumber and Capybara to write automated acceptance tests for Rotten Tomatoes website.', images: 'n/a'},
{project_title: 'Skills',
 description: 'General Purpose Programming Languages',
 images: 'Java, C, Python 2 and 3, Ruby, Haskell'},
{project_title: 'Skills',
 description: 'Database Management',
 images: 'PostgreSQL, SQLite'},
{project_title: 'Skills',
 description: 'Frontend Programming Languages',
 images: 'HTML, CSS, HTML.erb, HAML'},
{project_title: 'Skills',
 description: 'Automated Testing',
 images: 'Rspec, Cucumber/Capybara, JUnit, SimpleCov code coverage'},
{project_title: 'Skills',
 description: 'Statistical Programming Languages',
 images: 'R, Julia'},
{project_title: 'Skills',
 description: 'Agile Methodology',
 images: 'Scrum Meetings, Test Driven Development, Behavior Driven Development, Black-Box Testing, Automated Unit and Acceptance Testing, Pair Programming, Design Documentation, Activity Diagrams, Use Case Diagrams, Sequence Diagrams, Velocity Tracking using Pivotal Tracker'},
{project_title: 'Skills',
 description: 'Programming Tools',
 images: 'Jupyter Notebook, Ruby-on-Rails, Heroku, Git'},
{project_title: 'Skills',
 description: 'Programming Classes',
 images: 'Data Structures (Java), Algorithms (Java), Object Oriented Software Development (OOSD) (Java), Computer Organization (Assembly), Engineering Problem Solving  II  (C), Engineering Problem Solving  with R (R) , Intro to Networks and their Connections (Python 2, 3), Optimization Techniques (Julia), Software Engineering Languages and Tools(SQL, Ruby, HTML, CSS), Programming Language Concepts (Haskell)'},
{project_title: 'Skills',
 description: 'Non-Programming CS Classes',
 images: 'Discrete Structures, Numerical Calculations, Statistics, Engineering Math I-V, Physics I-II, Computational Epidemiology, Logic in Computer Science'},
]
descriptions.each do |description|
  Description.create!(description)
end